DROP TABLE IF EXISTS book;

CREATE TABLE book (
                       ID UUID PRIMARY KEY,
                       AUTHOR_NAME VARCHAR(250) NOT NULL,
                       BOOK_TITLE VARCHAR(250) NOT NULL,
                       BOOK_URL VARCHAR(250) NOT NULL,
                       BOOK_COVER_URL VARCHAR(250) NOT NULL,
                       BOOK_GENRES VARCHAR(250) NOT NULL,
                       BOOK_EDITORIAL_NOTES TEXT NOT NULL,
                       BOOK_AVERAGE_RATING DECIMAL(2) NOT NULL,
                       BOOK_RATINGS INT NOT NULL
);

INSERT INTO book (ID, AUTHOR_NAME, BOOK_TITLE, BOOK_URL, BOOK_COVER_URL, BOOK_GENRES, BOOK_EDITORIAL_NOTES, BOOK_AVERAGE_RATING, BOOK_RATINGS) VALUES
('4a739246-02ef-4211-a76c-03af3419b91d', 'Elif Shafak', 'The Island of Missing Trees', 'https://books.apple.com/us/book/the-island-of-missing-trees/id1571283566', 'https://is5-ssl.mzstatic.com/image/thumb/Publication126/v4/8d/b2/94/8db2948a-4e99-1027-e416-1de5cb19328b/1034267102.jpg/400x700bb.jpg', 'Fiction & Literature,Books', 'Set in Cyprus and London between 1974 and the late 2010s, Elif Shafak‚Äôs tale of star-crossed lovers is so captivating it feels almost magical at times. Of course, it doesn‚Äôt hurt that half of the novel is narrated by an exceptionally wise fig tree. <i>The Island of Missing Trees</i> tells the story of teenage sweethearts Kostas and Defne‚Äîhe a Greek Christian, she a Turkish Muslim‚Äîand their ongoing struggles after leaving a divided postcolonial Cyprus. Shafak‚Äôs narrative sparkles with undercurrents of beauty and joy even as it explores themes of family, grief, and trauma. We especially adored the comic relief of Aunt Meryem, with her Marilyn Monroe‚Äìthemed suitcases and her staunch unwillingness to mind her own business. This book is a profound celebration of love and the many ways that it endures across distance and time.', 4.1, 28),
('aeef66f5-e97d-42d8-9f10-481d815f308b', 'Kekla Magoon', 'Revolution in Our Time: The Black Panther Party‚Äôs Promise to the People', 'https://books.apple.com/us/book/revolution-in-our-time-the-black-panther-partys/id1574214141', 'https://is5-ssl.mzstatic.com/image/thumb/Publication125/v4/59/a5/b4/59a5b4cc-9af8-3da4-1359-dc4e35ea49d6/9781536223422.jpg/400x700bb.jpg', 'Social Studies,Books,Young Adult,History,Biography', '‚ÄúBlack power!‚Äù wasn‚Äôt just a slogan in 1966. As YA novelist Kekla Magoon explores in this groundbreaking history, it was a revolutionary call to action. In the mid-20th century, Black men and women came together to challenge the centuries of systematic oppression that made up the American status quo, eventually morphing into an organized movement called the Black Panther Party for Self-Defense. Magoon‚Äôs rigorously researched book digs into that group‚Äôs accomplishments and the unconscionably unjust challenges it faced‚Äîwhich are all too often ignored in history books and pop culture. Magoon does more than give context to the images we‚Äôve seen of beret-clad men with rifles. She details how the bulk of the party‚Äôs tireless efforts went into educating, feeding, and building Black communities. We were astounded by everything we learned about the Black Panthers‚Äô true political ideals, and how the U.S. government still somehow justified suppressing them. Although it was written for young adults, <i>Revolution in Our Time</i> is required reading for anyone who wants to learn the true story behind one of America‚Äôs most notoriously misunderstood political movements.', 0, 0),
('a0d104c8-eaaf-4d4e-93b5-5fc826dd30eb', 'Priya Fielding-Singh', 'How the Other Half Eats', 'https://books.apple.com/us/book/how-the-other-half-eats/id1552672105', 'https://is4-ssl.mzstatic.com/image/thumb/Publication115/v4/ab/98/01/ab98014d-deab-e60c-58d9-463f528b3eab/9780316427272.jpg/400x700bb.jpg', 'Social Science,Books,Nonfiction,Health, Mind & Body,Diet & Nutrition', 'In writing this fascinating and informative book, ethnographer Priya Fielding-Singh interviewed nearly 200 parents (mostly moms) about their families‚Äô diets. Her findings were almost shockingly consistent. Overwhelmingly, mothers feel drained and alone in their worries about their children‚Äôs nutrition, experiencing near-constant stress about how to provide good food that‚Äôs healthy and tasty. Fielding-Singh follows four particular families across racial and class boundaries, and learns that whether the issue is getting overscheduled children to the dinner table or simply having enough food to eat, it‚Äôs clear that all families and children could use more empathy and support. If you‚Äôve ever found yourself worrying about how to feed your kids a nutritious meal they‚Äôll actually enjoy, <i>How the Other Half Eats</i> will leave you feeling heard.&#xa0;', 5, 1),
('ab2deb80-d49d-4452-b0a2-62150ea7b7e2', 'Sang Young Park & Anton Hur', 'Love in the Big City', 'https://books.apple.com/us/book/love-in-the-big-city/id1558192250', 'https://is1-ssl.mzstatic.com/image/thumb/Publication115/v4/1c/42/d1/1c42d151-a816-e378-8df2-5ff659d5fb35/9780802158796.jpg/400x700bb.jpg', 'Literary,Books,Fiction & Literature,Nonfiction,Social Science,Society,Gay', 'You can feel the urgency bouncing off the pages of Sang Young Park‚Äôs electrifying debut, one of the first gay novels ever published in South Korea. <i>Love in the Big City</i>‚Äôs massive popularity in that country‚Äîit sold out nine printings‚Äîspeaks to a seismic shift in attitudes towards queer experiences. There‚Äôs also the universal appeal of the novel‚Äôs twentysomething narrator, Young, and his search for love and meaning in a vast urban playground. Told in four parts, this exuberant and poignant story takes us along for the ride as Young navigates affairs, friendships, and his fraught relationship with his mother. This is a frenetic, can‚Äôt-miss chronicle of young adulthood in all its uncertainty and joy.', 4, 4),
('5ace769a-0088-4494-9be6-5684f210e2bb', 'Darcie Little Badger', 'A Snake Falls to Earth', 'https://books.apple.com/us/book/a-snake-falls-to-earth/id1585049721', 'https://is4-ssl.mzstatic.com/image/thumb/Publication116/v4/35/1a/1e/351a1eee-1c2b-1ad7-a47b-7774f06a879b/9781646141142.jpg/400x700bb.jpg', 'Fantasy,Books,Young Adult,Fiction,Horror, Monsters & Ghosts,Culture, Places & People', 'With rich symbolism and gorgeous imagination, Darcie Little Badger has created a vivid new folktale. Texas teen Nina is trying to understand her family‚Äôs odd history‚Äîand why it involves such incredibly long lifespans. Meanwhile, in the alternate universe known as the Reflecting World, young Oli, a snake person, is trying to figure out why his toad neighbor suddenly seems to be dying. When the girl and the snake‚Äôs paths cross on the eve of a Gulf Coast hurricane, their fast friendship is immediately tested by dangers that go beyond weather. With the lightest touch, Little Badger weaves warnings about ecology, cultural loss, climate change, and extinction of both species and languages into this captivating story. She loads <i>A Snake Falls to Earth</i> with everything that great stories have passed down through oral traditions. That makes this novel, like all folktales, a story that becomes more powerful the more that it‚Äôs shared.', 5, 1),
('1db2198c-9830-4a1c-9270-5d288bc6a1e5', 'H. W. Brands', 'Our First Civil War', 'https://books.apple.com/us/book/our-first-civil-war/id1553001690', 'https://is5-ssl.mzstatic.com/image/thumb/Publication114/v4/9b/a0/51/9ba05139-e1c1-b7d8-4931-a1509b0eb637/9780385546522.d.jpg/400x700bb.jpg', 'United States,Books,History,Biographies & Memoirs', 'Experience the American Revolution as the riveting, dangerous thrill ride that it was. In his compulsively readable book, historian H. W. Brands focuses on the stories of George Washington and Benjamin Franklin as they each become central figures in the complex fight between the Patriots and the Loyalists. With visceral detail and meticulous research, Brands offers an in-depth examination of this pivotal, volatile period in American history and all its intense battles. We loved following the intimate stories of the young, inexperienced Washington and the fascinatingly eccentric Franklin. Brands lets us see these legendary heroes as real people while keeping us in awe of their extraordinary accomplishments. Exhilarating and reflective, <i>Our First Civil War</i> makes American history read like a page-turning thriller.', 4, 3),
('f98e39f7-5cce-4140-af69-d0d58daa5a1a', 'Alison Macleod', 'Tenderness', 'https://books.apple.com/us/book/tenderness/id1566547772', 'https://is3-ssl.mzstatic.com/image/thumb/Publication115/v4/ec/bb/b7/ecbbb707-1b41-873c-e237-623e358fea07/1033983030.jpg/400x700bb.jpg', 'Literary,Books,Fiction & Literature,Historical', 'In this moving historical novel, wonderful things happen when art stands up to censorship. British Canadian author Alison MacLeod explores the inspiring story behind author D. H. Lawrence‚Äôs brave and controversial novel <i>Lady Chatterley‚Äôs Lover</i>. In 1928, Lawrence published the novel privately, knowing that its honest depiction of sexuality would prompt swift censorship. But it wasn‚Äôt until 1960‚Äîthree decades after the author‚Äôs death‚Äîthat the full text was finally made available to the public, prompting a British trial that ended in a groundbreaking win for the publisher. MacLeod deftly weaves factual accounts together with fictionalized characters and events, bringing to life the struggles around sensuality, class, and freedom of speech that marked both of these turbulent historical periods. <i>Tenderness</i> is a story about love‚Äîand the fight to celebrate it.', 0, 0);


CREATE TABLE book_reviews (
                      ID UUID PRIMARY KEY,
                      BOOK_ID UUID references book(ID),
                      REVIEW TEXT,
                      RATING DECIMAL(2) NOT NULL,
                      USER_EMAIL VARCHAR(250) NOT NULL,
                      DATE_TIME DATETIME
);

ALTER TABLE book_reviews ADD CONSTRAINT book_user UNIQUE(BOOK_ID, USER_EMAIL);

INSERT INTO review (ID, BOOK_ID, REVIEW, RATING, USER_EMAIL, DATE_TIME) VALUES
('8b993f98-5439-4cf4-9d8f-7d016b4358a2', '4a739246-02ef-4211-a76c-03af3419b91d', 'Great Book', 4.5, 'ishmeetkohli@gmail.com', '2008-11-11 13:23:44'),
('ea310f99-c8fc-4ecb-9f1f-9dd87a79d7f4', '4a739246-02ef-4211-a76c-03af3419b91d', 'Totally love this book', 5.0, 'harneetkaur@gmail.com', '2008-11-09 15:45:21'),
('08532f50-8b36-424f-97c1-fffda93592d2', '4a739246-02ef-4211-a76c-03af3419b91d', 'Enjoyed the book a lot', 4.0, 'randomPerson@gmail.com', '2008-11-11 11:12:01'),
('f2182d82-7d93-4004-baf9-6cc02c7a88b6', '4a739246-02ef-4211-a76c-03af3419b91d', 'Enjoyed the book a lot', 3.5, 'dummy_1234@gmail.com', '2008-10-29 14:56:59');